### ISSUE TITLE
GetRootfolder() logs to build output

### ISSUE THREAD

**Issue by joshka** [madskristensen/WebEssentials2012#3]
Hiya,
The following is in my build window when I build my solution. Running WE 2012 v3.2

7/10/2013 10:06:24 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
at EnvDTE.Properties.Item(Object index)
at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
at EnvDTE.Properties.Item(Object index)
at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
7/10/2013 10:06:24 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
at EnvDTE.Properties.Item(Object index)
at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
at EnvDTE.Properties.Item(Object index)
at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
... <snip>

**Comment by madskristensen** [comment]
Fixed

**Comment by adrianp74** [comment]
This is NOT fixed. It's still occurring with the latest release 3.5
